const $=s=>document.querySelector(s);let csrf="";let state=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function sb(){const cfg=await fetch("/api/config").then(r=>r.json());const mod=await import("https://esm.sh/@supabase/supabase-js@2.117.3");return mod.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:true}})}
let client;
async function getClient(){if(!client)client=await sb();return client}
async function csrfToken(){if(csrf)return csrf;const r=await fetch("/api/csrf");const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to initialize security token.");csrf=d.csrfToken;return csrf}
async function api(method="GET",body){const s=await getClient(),session=(await s.auth.getSession()).data.session;if(!session)throw Error("Sign in first.");const headers={Authorization:"Bearer "+session.access_token,Accept:"application/json"};if(method!=="GET"){headers["Content-Type"]="application/json";headers["X-CSRF-Token"]=await csrfToken()}const r=await fetch("/api/admin",{method,headers,body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Admin request failed.");return d}
function msg(t,error=false){const m=$("#message");m.textContent=t;m.className="message "+(error?"error":"ok")}
function render(){const d=state;$("#stats").innerHTML=[["Products",d.stats.products],["Active",d.stats.activeProducts],["Orders",d.stats.orders],["Demo revenue","₹"+Number(d.stats.revenueInr).toLocaleString("en-IN")]].map(x=>'<div class="stat"><span>'+esc(x[0])+'</span><b>'+esc(x[1])+"</b></div>").join("");$("#product-count").textContent=d.products.length+" products";const byProduct={};d.variants.forEach(v=>(byProduct[v.product_id]??=[]).push(v));$("#products").innerHTML=d.products.map(p=>'<article class="product"><div class="product-head"><div><h3>'+esc(p.name)+'</h3><div class="muted">'+esc(p.slug)+' · ₹'+Number(p.price_inr).toLocaleString("en-IN")+'</div></div><label><input type="checkbox" data-active="'+p.id+'" '+(p.active?"checked":"")+'> active</label></div><div class="row"><input aria-label="Price" type="number" min="0" value="'+esc(p.price_inr)+'" data-price="'+p.id+'"><button data-save-price="'+p.id+'">Save price</button></div><div class="row">'+(byProduct[p.id]||[]).map(v=>'<label>'+esc(v.size)+' <input aria-label="'+esc(v.size)+' stock" type="number" min="0" max="100000" value="'+esc(v.stock)+'" data-stock="'+v.id+'"><button data-save-stock="'+v.id+'">Save</button></label>').join("")+"</div></article>").join("");$("#orders").innerHTML=d.orders.map(o=>'<tr><td>#'+esc(String(o.id).slice(0,8))+'</td><td>'+esc(o.customer_name||"—")+'<br><span class="muted">'+esc(o.customer_email)+'</span></td><td>₹'+Number(o.total_inr).toLocaleString("en-IN")+'</td><td><select data-status="'+o.id+'">'+["pending","paid","processing","shipped","delivered","cancelled"].map(s=>'<option '+(s===o.status?"selected":"")+'>'+s+"</option>").join("")+'</select></td><td>'+esc(new Date(o.created_at).toLocaleString("en-IN"))+'</td></tr>').join("")}
async function load(){try{msg("Loading…");state=await api();render();msg("Console ready.");}catch(e){msg(e.message,true)}}
document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;try{if(b.id==="refresh"){await load();return}if(b.id==="signout"){const c=await getClient();await c.auth.signOut();location.href="/";return}if(b.dataset.savePrice){await api("PATCH",{type:"product",id:b.dataset.savePrice,patch:{price_inr:Number(document.querySelector('[data-price="'+b.dataset.savePrice+'"]').value)}});await load();return}if(b.dataset.saveStock){await api("PATCH",{type:"variant",id:b.dataset.saveStock,stock:Number(document.querySelector('[data-stock="'+b.dataset.saveStock+'"]').value)});await load();return}}catch(e){msg(e.message,true)}});
document.addEventListener("change",async e=>{if(e.target.dataset.active){try{await api("PATCH",{type:"product",id:e.target.dataset.active,patch:{active:e.target.checked}});await load()}catch(err){e.target.checked=!e.target.checked;msg(err.message,true)}}if(e.target.dataset.status){try{await api("PATCH",{type:"order",id:e.target.dataset.status,status:e.target.value});await load()}catch(err){msg(err.message,true)}}});
(async()=>{try{const c=await getClient();const s=(await c.auth.getSession()).data.session;if(!s){msg("Sign in through the storefront first, then open /admin.html.",true);return}await load()}catch(e){msg(e.message,true)}})();
