const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const categories=[['DRESSES','cat-dresses.jpg'],['TOPS','cat-tops.jpg'],['CO-ORD SETS','cat-coord.jpg'],['JACKETS','cat-jackets.jpg'],['ACCESSORIES','cat-accessories.jpg'],['LOUNGEWEAR','cat-lounge.jpg']];
const products=[
 ['Linen Maxi Dress','₹2,499','DRESSES','product-1.jpg','Lightweight linen with an effortless everyday silhouette.',['S','M','L','XL']],
 ['Floral Wrap Dress','₹2,499','DRESSES','product-2.jpg','A feminine floral wrap dress made for sunny days.',['S','M','L','XL']],
 ['Satin Cowl Top','₹1,499','TOPS','product-3.jpg','A fluid satin top with an elegant cowl neckline.',['S','M','L']],
 ['Pleated Midi Skirt','₹1,899','SKIRTS','product-4.jpg','A graceful pleated skirt that moves with you.',['S','M','L']],
 ['Linen Co-ord Set','₹2,799','CO-ORD SETS','product-5.jpg','A relaxed matching set for polished everyday dressing.',['S','M','L','XL']]
];
const articles=[['5 Ways to Style Linen This Summer','Simple styling ideas for breathable, timeless linen pieces.'],['Wardrobe Staples You Need','The versatile essentials that make getting dressed easier.'],['Neutral Tones, Endless Possibilities','Build a calm, coordinated wardrobe with neutral shades.']];
const heroSlides=[{title:'Confidence\\nLooks Good\\nOn You.',text:'Effortless styles for your everyday moments.',image:'/hero-photo.jpg'},{title:'Everyday\\nElegance.',text:'Timeless pieces designed for effortless styling.',image:'/editorial.jpg'},{title:'Wear Your\\nStory.',text:'Discover pieces that feel like you.',image:'/journal-1.jpg'}];
const readJSON=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key)||'');return v??fallback}catch{return fallback}};
const normalizeCart=items=>Array.isArray(items)?items.map(x=>typeof x==='number'?{i:x,size:'M',qty:1}:x).filter(x=>x&&Number.isInteger(x.i)&&x.i>=0&&x.i<products.length&&typeof x.size==='string'&&products[x.i][5].includes(x.size)&&Number.isInteger(x.qty)&&x.qty>0):[];
const storedWish=readJSON('mirae-wish',[]);const state={cart:normalizeCart(readJSON('mirae-cart',[])),wish:Array.isArray(storedWish)?storedWish.filter(i=>Number.isInteger(i)&&i>=0&&i<products.length):[],filter:'all'};
let lastFocus=null;
const asset=n=>`/${n}`;
function save(){try{localStorage.setItem('mirae-cart',JSON.stringify(state.cart));localStorage.setItem('mirae-wish',JSON.stringify(state.wish))}catch{}}
function openModal(title,body,ready){lastFocus=document.activeElement;$('#modal-content').innerHTML=`<h2 id="modal-title">${title}</h2>${body}`;$('#overlay').hidden=false;document.body.classList.add('modal-open');ready?.();setTimeout(()=>$('#overlay .modal button,#overlay .modal input,#overlay .modal textarea')?.focus(),0)}
function closeModal(){if($('#overlay').hidden)return;$('#overlay').hidden=true;document.body.classList.remove('modal-open');lastFocus?.focus?.()}
function renderCategories(){$('#categories').innerHTML=categories.map(([n,img])=>`<div class="category-wrap"><button class="category" data-category="${n}" aria-label="Shop ${n.toLowerCase()}"><img src="${asset(img)}" alt="${n}" loading="lazy"></button><span>${n}</span></div>`).join('')}
function renderProducts(){const rows=products.map((p,i)=>({p,i})).filter(x=>state.filter==='all'||x.p[2]===state.filter);$('#products').innerHTML=rows.map(({p,i})=>`<article class="product"><button class="heart" data-wish="${i}" aria-label="${state.wish.includes(i)?'Remove':'Add'} ${p[0]} ${state.wish.includes(i)?'from':'to'} wishlist">${state.wish.includes(i)?'♥':'♡'}</button><button class="product-image" data-product="${i}" aria-label="View ${p[0]}"><img src="${asset(p[3])}" alt="${p[0]}" loading="lazy"></button><h3>${p[0]}</h3><p class="price">${p[1]}</p><div class="swatches" aria-hidden="true"><i></i><i></i><i></i></div><button class="primary" data-add="${i}">ADD TO BAG</button><button class="text-button" data-product="${i}">VIEW DETAILS</button></article>`).join('')||'<p>No pieces in this collection yet.</p>'}
function cartCount(){return state.cart.reduce((n,x)=>n+x.qty,0)}
function updateCart(){save();$('#cart-count').textContent=cartCount();$('#cart-items').innerHTML=state.cart.length?state.cart.map((x,line)=>{const p=products[x.i];return`<div class="cart-line"><span><b>${p[0]}</b><small>Size ${x.size} · ${p[1]}</small><span class="qty"><button data-qty="-1" data-line="${line}" aria-label="Decrease quantity">−</button><b>${x.qty}</b><button data-qty="1" data-line="${line}" aria-label="Increase quantity">+</button></span></span><button data-remove="${line}" aria-label="Remove ${p[0]}">×</button></div>`}).join(''):'<p>Your bag is empty.</p>';const total=state.cart.reduce((s,x)=>s+Number(products[x.i][1].replace(/[^0-9]/g,''))*x.qty,0);$('#cart-total').textContent=`₹${total.toLocaleString('en-IN')}`}
function showCart(){$('#drawer').classList.add('open');updateCart()}
function addToCart(i,size='M'){const existing=state.cart.find(x=>x.i===i&&x.size===size);if(existing)existing.qty++;else state.cart.push({i,size,qty:1});showCart()}
function showProduct(i){const p=products[i];openModal(p[0],`<img class="modal-product-image" src="${asset(p[3])}" alt="${p[0]}"><p>${p[4]}</p><h3>${p[1]}</h3><p>Category: ${p[2]}</p><label for="product-size"><b>Size</b></label><select id="product-size">${p[5].map(s=>`<option value="${s}">${s}</option>`).join('')}</select><button class="primary" data-modal-add="${i}">ADD TO BAG →</button>`)}
function showWishlist(){openModal('Your Wishlist',state.wish.map(i=>`<p><b>${products[i][0]}</b> — ${products[i][1]} <button data-product="${i}">View</button></p>`).join('')||'<p>Your wishlist is waiting for a little love ♡</p>')}
function showSearch(){openModal('Find your style','<p>Search products by name or category.</p><label class="sr-only" for="search-input">Search products</label><input id="search-input" placeholder="Try linen, dresses or tops" autocomplete="off"><div id="search-results"></div>');const input=$('#search-input');const render=()=>{const q=input.value.toLowerCase();$('#search-results').innerHTML=products.map((p,i)=>({p,i})).filter(x=>`${x.p[0]} ${x.p[2]}`.toLowerCase().includes(q)).map(x=>`<p><button class="text-button" data-product="${x.i}">${x.p[0]} — ${x.p[1]}</button></p>`).join('')||'<p>No matching styles found.</p>'};input.addEventListener('input',render);render();input.focus()}
function showAccount(){openModal('Welcome to MIRAE','<p>Sign in to save your wishlist and track orders.</p><form id="account-form"><input type="email" required autocomplete="email" placeholder="Email address"><input type="password" required minlength="4" autocomplete="current-password" placeholder="Password"><button class="primary">CONTINUE</button></form><p id="account-message"></p>');$('#account-form').addEventListener('submit',e=>{e.preventDefault();$('#account-message').textContent='Demo sign-in complete. Connect authentication for real accounts.';e.target.reset()})}
function showJournal(i=null){openModal(i===null?'From the Journal':articles[i][0],i===null?articles.map((a,j)=>`<p><b>${a[0]}</b><br>${a[1]}<br><button class="text-button" data-article="${j}">READ ARTICLE →</button></p>`).join(''):`<p>${articles[i][1]}</p><p>Read more styling inspiration in the next MIRAE editorial edition.</p>`)}
function showContact(){openModal('We’re here to help','<p>Our support team is happy to help.</p><form id="contact-form"><input required autocomplete="name" placeholder="Your name"><input type="email" required autocomplete="email" placeholder="Email address"><textarea required placeholder="How can we help?"></textarea><button class="primary">SEND MESSAGE</button></form><p id="contact-message"></p>');$('#contact-form').addEventListener('submit',e=>{e.preventDefault();$('#contact-message').textContent='Thanks! Your demo message was recorded locally.';e.target.reset()})}
function showMenu(){openModal('MIRAE Menu','<div class="menu-links"><button data-scroll="#new">New Arrivals</button><button data-scroll="#shop">Shop</button><button data-scroll="#collections">Collections</button><button data-scroll="#about">About</button><button data-scroll="#journal">Journal</button></div>')}
function setHero(i){const s=heroSlides[i];if(!s)return;$('.hero h1').innerHTML=s.title.replace(/\\n/g,'<br>');$('.hero-copy>p:not(.eyebrow)').textContent=s.text;$('.hero-image img').src=s.image;$$('[data-hero]').forEach((b,n)=>b.classList.toggle('active',n===i))}
document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;const d=t.dataset,a=d.action;if(d.action||d.filter!==undefined||d.category||d.scroll||d.product!==undefined||d.add!==undefined||d.modalAdd!==undefined||d.wish!==undefined||d.article!==undefined||d.remove!==undefined||d.qty!==undefined)e.preventDefault();
if(d.add!==undefined){showProduct(+d.add);return}
if(d.modalAdd!==undefined){addToCart(+d.modalAdd,$('#product-size')?.value||'M');closeModal();return}
if(d.remove!==undefined){state.cart.splice(+d.remove,1);updateCart();return}
if(d.qty!==undefined){const line=+d.line;if(!state.cart[line])return;state.cart[line].qty+=+d.qty;if(state.cart[line].qty<=0)state.cart.splice(line,1);updateCart();return}
if(d.product!==undefined){showProduct(+d.product);return}
if(d.wish!==undefined){const i=+d.wish;state.wish=state.wish.includes(i)?state.wish.filter(x=>x!==i):[...state.wish,i];renderProducts();save();return}
if(d.article!==undefined){showJournal(+d.article);return}
if(d.category){state.filter=d.category;renderProducts();$('#new').scrollIntoView({behavior:'smooth'});return}
if(d.filter!==undefined){state.filter='all';renderProducts();$('#new').scrollIntoView({behavior:'smooth'});return}
if(d.scroll){closeModal();document.querySelector(d.scroll)?.scrollIntoView({behavior:'smooth'});return}
if(d.hero!==undefined){setHero(+d.hero);return}
if(a==='search')return showSearch();if(a==='account')return showAccount();if(a==='wishlist')return showWishlist();if(a==='journal')return showJournal();if(a==='read')return showJournal(0);if(a==='contact')return showContact();if(a==='checkout'){const n=cartCount();$('#drawer').classList.remove('open');openModal('Checkout',`<p>${n} item(s) in your bag.</p><p>This is a demo checkout screen. Connect Razorpay/Stripe and an order database for real purchases.</p><button class="primary" data-action="close">CONTINUE SHOPPING</button>`);return}if(a==='menu')return showMenu();if(a==='close')return closeModal();if(a==='cart')return showCart();if(a==='close-cart'){$('#drawer').classList.remove('open');return}});
$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#overlay').hidden)closeModal();else $('#drawer').classList.remove('open')}});
$('#newsletter').addEventListener('submit',e=>{e.preventDefault();openModal('You’re on the list ♡','<p>Thank you for subscribing to MIRAE updates.</p>');e.target.reset()});
renderCategories();renderProducts();updateCart();