const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const categories=[['DRESSES','cat-dresses.jpg'],['TOPS','cat-tops.jpg'],['CO-ORD SETS','cat-coord.jpg'],['JACKETS','cat-jackets.jpg'],['ACCESSORIES','cat-accessories.jpg'],['LOUNGEWEAR','cat-lounge.jpg']];
const products=[['Linen Maxi Dress','₹2,499','DRESSES','product-1.jpg','Lightweight linen with an effortless everyday silhouette.'],['Floral Wrap Dress','₹2,499','DRESSES','product-2.jpg','A feminine floral wrap dress made for sunny days.'],['Satin Cowl Top','₹1,499','TOPS','product-3.jpg','A fluid satin top with an elegant cowl neckline.'],['Pleated Midi Skirt','₹1,899','SKIRTS','product-4.jpg','A graceful pleated skirt that moves with you.'],['Linen Co-ord Set','₹2,799','CO-ORD SETS','product-5.jpg','A relaxed matching set for polished everyday dressing.']];
const articles=[['5 Ways to Style Linen This Summer','Simple styling ideas for breathable, timeless linen pieces.'],['Wardrobe Staples You Need','The versatile essentials that make getting dressed easier.'],['Neutral Tones, Endless Possibilities','Build a calm, coordinated wardrobe with neutral shades.']];
const state={cart:JSON.parse(localStorage.getItem('mirae-cart')||'[]'),wish:JSON.parse(localStorage.getItem('mirae-wish')||'[]'),filter:'all'};const asset=n=>`/${n}`;
function save(){localStorage.setItem('mirae-cart',JSON.stringify(state.cart));localStorage.setItem('mirae-wish',JSON.stringify(state.wish))}
function openModal(title,body,ready){$('#modal-content').innerHTML=`<h2>${title}</h2>${body}`;$('#overlay').hidden=false;document.body.classList.add('modal-open');ready?.()}
function closeModal(){$('#overlay').hidden=true;document.body.classList.remove('modal-open')}
function renderCategories(){$('#categories').innerHTML=categories.map(([n,img])=>`<div class="category-wrap"><button class="category" data-category="${n}"><img src="${asset(img)}" alt="${n}"></button><span>${n}</span></div>`).join('')}
function renderProducts(){const rows=products.map((p,i)=>({p,i})).filter(x=>state.filter==='all'||x.p[2]===state.filter);$('#products').innerHTML=rows.map(({p,i})=>`<article class="product"><button class="heart" data-wish="${i}">${state.wish.includes(i)?'♥':'♡'}</button><button class="product-image" data-product="${i}"><img src="${asset(p[3])}" alt="${p[0]}" loading="lazy"></button><h3>${p[0]}</h3><p class="price">${p[1]}</p><div class="swatches"><i></i><i></i><i></i></div><button class="primary" data-add="${i}">ADD TO BAG</button><button class="text-button" data-product="${i}">VIEW DETAILS</button></article>`).join('')||'<p>No pieces in this collection yet.</p>'}
function updateCart(){save();$('#cart-count').textContent=state.cart.length;$('#cart-items').innerHTML=state.cart.length?state.cart.map((i,line)=>`<div class="cart-line"><span>${products[i][0]}<small>${products[i][1]}</small></span><button data-remove="${line}">×</button></div>`).join(''):'<p>Your bag is empty.</p>';const total=state.cart.reduce((s,i)=>s+Number(products[i][1].replace(/[^0-9]/g,'')),0);$('#cart-total').textContent=`₹${total.toLocaleString('en-IN')}`}
function showCart(){$('#drawer').classList.add('open');updateCart()}
function showProduct(i){const p=products[i];openModal(p[0],`<img class="modal-product-image" src="${asset(p[3])}" alt="${p[0]}"><p>${p[4]}</p><h3>${p[1]}</h3><p>Category: ${p[2]}</p><button class="primary" data-add="${i}">ADD TO BAG →</button>`)}
function showWishlist(){openModal('Your Wishlist',state.wish.map(i=>`<p><b>${products[i][0]}</b> — ${products[i][1]} <button data-product="${i}">View</button></p>`).join('')||'<p>Your wishlist is waiting for a little love ♡</p>')}
function showSearch(){openModal('Find your style','<p>Search products by name or category.</p><input id="search-input" placeholder="Try linen, dresses or tops"><div id="search-results"></div>');const input=$('#search-input');const render=()=>{const q=input.value.toLowerCase();$('#search-results').innerHTML=products.map((p,i)=>({p,i})).filter(x=>`${x.p[0]} ${x.p[2]}`.toLowerCase().includes(q)).map(x=>`<p><button class="text-button" data-product="${x.i}">${x.p[0]} — ${x.p[1]}</button></p>`).join('')||'<p>No matching styles found.</p>'};input.addEventListener('input',render);render();input.focus()}
function showAccount(){openModal('Welcome to MIRAE','<p>Sign in to save your wishlist and track orders.</p><form id="account-form"><input type="email" required placeholder="Email address"><input type="password" required minlength="4" placeholder="Password"><button class="primary">CONTINUE</button></form><p id="account-message"></p>');$('#account-form').addEventListener('submit',e=>{e.preventDefault();$('#account-message').textContent='Demo sign-in complete. Connect authentication for real accounts.';e.target.reset()})}
function showJournal(i=null){openModal(i===null?'From the Journal':articles[i][0],i===null?articles.map((a,j)=>`<p><b>${a[0]}</b><br>${a[1]}<br><button class="text-button" data-article="${j}">READ ARTICLE →</button></p>`).join(''):`<p>${articles[i][1]}</p><p>Read more styling inspiration in the next MIRAE editorial edition.</p>`)}
function showContact(){openModal('We’re here to help','<p>Our support team is happy to help.</p><form id="contact-form"><input required placeholder="Your name"><input type="email" required placeholder="Email address"><textarea required placeholder="How can we help?"></textarea><button class="primary">SEND MESSAGE</button></form><p id="contact-message"></p>');$('#contact-form').addEventListener('submit',e=>{e.preventDefault();$('#contact-message').textContent='Thanks! Your demo message was recorded locally.';e.target.reset()})}
function showMenu(){openModal('MIRAE Menu','<div class="menu-links"><button data-scroll="#new">New Arrivals</button><button data-scroll="#shop">Shop</button><button data-scroll="#collections">Collections</button><button data-scroll="#about">About</button><button data-scroll="#journal">Journal</button></div>')}
document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;const d=t.dataset,a=d.action;if(d.action||d.filter!==undefined||d.category||d.scroll||d.product!==undefined||d.add!==undefined||d.wish!==undefined||d.article!==undefined||d.remove!==undefined)e.preventDefault();if(d.add!==undefined){state.cart.push(+d.add);showCart();return}if(d.remove!==undefined){state.cart.splice(+d.remove,1);updateCart();return}if(d.product!==undefined){showProduct(+d.product);return}if(d.wish!==undefined){const i=+d.wish;state.wish=state.wish.includes(i)?state.wish.filter(x=>x!==i):[...state.wish,i];renderProducts();save();return}if(d.article!==undefined){showJournal(+d.article);return}if(d.category){state.filter=d.category;renderProducts();$('#new').scrollIntoView({behavior:'smooth'});return}if(d.filter!==undefined){state.filter='all';renderProducts();$('#new').scrollIntoView({behavior:'smooth'});return}if(d.scroll){closeModal();document.querySelector(d.scroll)?.scrollIntoView({behavior:'smooth'});return}if(a==='search')return showSearch();if(a==='account')return showAccount();if(a==='wishlist')return showWishlist();if(a==='journal')return showJournal();if(a==='read')return showJournal(0);if(a==='contact')return showContact();if(a==='checkout'){const n=state.cart.length;closeModal();$('#drawer').classList.remove('open');openModal('Checkout',`<p>${n} item(s) in your bag.</p><p>This is a demo checkout screen. Connect Razorpay/Stripe and an order database for real purchases.</p><button class="primary" data-action="close">CONTINUE SHOPPING</button>`);return}if(a==='menu')return showMenu();if(a==='close')return closeModal();if(a==='cart')return showCart();if(a==='close-cart'){$('#drawer').classList.remove('open');closeModal()}});
$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closeModal()});$('#newsletter').addEventListener('submit',e=>{e.preventDefault();openModal('You’re on the list ♡','<p>Thank you for subscribing to MIRAE updates.</p>');e.target.reset()});renderCategories();renderProducts();updateCart();